In [1]:
#Diffusion Testing
#Imports
import time
import random
import cv2
import os
import math
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.widgets import Cursor
from PIL import Image
import hashlib
get_ipython().run_line_magic('matplotlib', 'inline')




def doRowColPermutationEncryption(img, rowList, colList):
    
    
    w,h = img.shape
    c =  np.zeros((w,h), dtype=np.int)
    c = img.copy()
    istep = h//2
   
    print('\nBefore permuation\n', img)
    #For the permutation of the rows
    for i in range(len(rowList)):
            #All cols of c and its row i is equal to all cols of img and the rowLits[i] row of img 
            c[i,:] = img[rowList[i],:]
 
    print('\nafter row permuation\n', c)
    
    c1 =  np.zeros((w,h), dtype=np.int)
    c1 = c.copy()
    
    for j in range(len(colList)):
            #All rows of c and its col j is equal to all rows of img and the colList[i] row of img 
            c1[:,j] = c[:,colList[j]]
     
  
    
    print('\nafter row col\n', c1)
    return c1


def doRowColPermutationDecryption(img, rowList, colList):
    
    w,h = img.shape
    c =  np.zeros((w,h), dtype=np.int)
    c = img.copy()
    istep = h//2
   
    print('\nBefore dedpermuation\n', img)
    for j in range(len(colList)):
            #All rows of c and its col j is equal to all rows of img and the colList[i] row of img 
            c[:,colList[j]] = img[:,j]
  
    print('\nafter col de permuation\n', c)
    c1 =  np.zeros((w,h), dtype=np.int)
    c1 = img.copy()
    
    #For the permutation of the rows
    for i in range(len(rowList)):
            #All cols of c and its row i is equal to all cols of img and the rowLits[i] row of img 
            c1[rowList[i],:] = c[i,:]
 
  
            
    print('\nafter per\n', c1)
    
    return c1



In [2]:
#Diffusion Testing
# #Imports
# import time
# import random
# import cv2
# import os
# import math
# import numpy as np
# import matplotlib.pyplot as plt
# from matplotlib.widgets import Cursor
# from PIL import Image
# import hashlib
# get_ipython().run_line_magic('matplotlib', 'inline')
# #We will test it with b=10, m=3, k=1
# # [_ _ {_] _ (_} _ _)_ 
# #  0 1  2  3  4  5 6 
# #l-rem = 6
# # to trigger on iRow = 3,1 
# #(l-rem-iRow)-(mPart-1)*(windowSize-strideSize) == windowSize
# #(6-prevIter) +2 = 

# windowSize = 3
# strideSize = 1

# ValueKey = [10,20,30,87,40,50,60,70]
# scale = 256

# def getPartsAcrossLength(b):
    
#     #For the image spanning over b units, finding the number of parts of size 64 and stride 16
#     #Over the span of 2*windowSize-strideSize, we have 2 windows and 1 stride of size
#     parts = int((b-windowSize)/ (windowSize-strideSize)) + 1;        
#     remaining = b-(parts-1)*(windowSize-strideSize) - windowSize
    
#     #Eg, b=768, w = 64, s = 16, w-s = 48 numParts = 1+(768-64)48 = 15
#     #Reamining = 768-(14)*48-64
#     return parts, remaining
    

# def colEnc(img):
    
#     l = len(img)
    
#     numParts, remaining = getPartsAcrossLength(l)
    
#     mPart = 1
#     miter = 0
#     b = np.zeros(l*1, dtype=np.int)
#     b = img.copy()

#     for iRow in range(0,l-remaining,1):
        
#         #If it is not the ending of the first part
#         if mPart == 1 and iRow == windowSize:
#             mPart = mPart +1
#             miter = miter-strideSize
            
#             for inRow in range(0,strideSize,1):
#                 #Diffusse again
#                 if miter == 0:
#                     #Take the current row, the last row, and correspoding row from the diffsion matrix and then scale
#                     b[miter] = (b[-1] + b[miter] + ValueKey[miter]) % scale
#                 else:
#                     #Else, take the current and the previous row with the diffusion matrix row
#                     b[miter] = (b[miter-1] + b[miter] + ValueKey[miter]) % scale
                
#                 miter= miter+1
#         elif mPart != 1 and iRow-(mPart-1)*(windowSize-strideSize) == windowSize:
#             mPart = mPart +1
#             miter = miter-strideSize
            
#             for inRow in range(0,strideSize,1):
#                 #Diffusse again
#                 if miter == 0:
#                     #Take the current row, the last row, and correspoding row from the diffsion matrix and then scale
#                     b[miter] = (b[-1] + b[miter] + ValueKey[miter]) % scale
#                 else:
#                     #Else, take the current and the previous row with the diffusion matrix row
#                     b[miter] = (b[miter-1] + b[miter] + ValueKey[miter]) % scale
                
#                 miter= miter+1

                
                
        
#         #Else
#         if miter == 0:
#             #Take the current row, the last row, and correspoding row from the diffsion matrix and then scale
#             b[miter] = (b[-1] + b[miter] + ValueKey[miter]) % scale
#         else:
#             #Else, take the current and the previous row with the diffusion matrix row
#             b[miter] = (b[miter-1] + b[miter] + ValueKey[miter]) % scale

                       
#         miter= miter+1
                
            
    
#     #For the remaining ones
#     for rem in range(0,remaining,1):
#         #Else
#         if miter == 0:
#             #Take the current row, the last row, and correspoding row from the diffsion matrix and then scale
#             b[miter] = (b[-1] + b[miter] + ValueKey[miter]) % scale
#         else:
#             #Else, take the current and the previous row with the diffusion matrix row
#             b[miter] = (b[miter-1] + b[miter] + ValueKey[miter]) % scale

                       
#         miter= miter+1
                
        
    
#     print('After col diff enc , img is \n',b)
    
#     return b

# def colDec(img):
    
    
#     arrLen = len(img)
    
#     numParts, remaining = getPartsAcrossLength(arrLen)
#     print('The parts across length are ', numParts, ' and remaining are ', remaining)
    
#     l = arrLen-1
#     mPart = 1
#     miter = l
#     b = np.zeros(l*1, dtype=np.int)
#     b = img.copy()

#     holdingNumber = 0
#     print('Before col diff dec  , img is \n',b)
    
#     for iRow in range(l,l-remaining,-1):
        
#         if miter == 0:
#             #Take the current row, the last row, and correspoding row from the diffsion matrix and then scale
#             b[miter] = (-b[-1] + b[miter] - ValueKey[miter]) % scale
#         else:
#             #Else, take the current and the previous row with the diffusion matrix row
#             b[miter] = (-b[miter-1] + b[miter] - ValueKey[miter]) % scale

#         print('Miter value for ',miter, 'is', b[miter])
#         miter= miter-1
    
#     print('l-remaining is ', l-remaining)
    
#     for iRow in range(0,l-remaining+1,1):
        
        
#         if mPart == 1 and iRow == windowSize:
#             mPart = mPart +1
#             miter = miter+strideSize
#             print('Now miter is ', miter)
#             holdingNumber = iRow
#             for inRow in range(0,strideSize,1):
#                 #Diffusse again
#                 if miter == 0:
#                     #Take the current row, the last row, and correspoding row from the diffsion matrix and then scale
#                     b[miter] = (-b[-1] + b[miter] - ValueKey[miter]) % scale
#                 else:
#                     #Else, take the current and the previous row with the diffusion matrix row
#                     b[miter] = (-b[miter-1] + b[miter] - ValueKey[miter]) % scale
                
#                 print('Miter value for ',miter, 'is', b[miter])
#                 miter= miter-1
                
#         elif mPart != 1 and iRow-(mPart-1)*(windowSize-strideSize) == holdingNumber:
#             mPart = mPart +1
#             miter = miter+strideSize
#             print('Now miter is ', miter)
#             for inRow in range(0,strideSize,1):
#                 #Diffusse again
#                 if miter == 0:
#                     #Take the current row, the last row, and correspoding row from the diffsion matrix and then scale
#                     b[miter] = (-b[-1] + b[miter] - ValueKey[miter]) % scale
#                 else:
#                     #Else, take the current and the previous row with the diffusion matrix row
#                     b[miter] = (-b[miter-1] + b[miter] - ValueKey[miter]) % scale
                
#                 print('Miter value for ',miter, 'is', b[miter])
#                 miter= miter-1
            
        
#         #Else
#         if miter == 0:
#             #Take the current row, the last row, and correspoding row from the diffsion matrix and then scale
#             b[miter] = (-b[-1] + b[miter] - ValueKey[miter]) % scale
#         else:
#             #Else, take the current and the previous row with the diffusion matrix row
#             b[miter] = (-b[miter-1] + b[miter] - ValueKey[miter]) % scale

#         print('Miter value for ',miter, 'is', b[miter])
#         miter= miter-1
                
            
    
#     print('After col diff dec  , img is \n',b)
    
#     return b

    
    
    
    
    
    
    




In [3]:

# img = [20,40,30,97,20,10,90,10]
# img = colEnc(img)
# img = colDec(img)

img = np.zeros((4,4))

for i in range(4):
    for j in range(4):
        img[i][j] = 50-i+5*j


rowList = [1,0,3,2]
colList = [2,0,3,1]

enc= doRowColPermutationEncryption(img, rowList, colList)
dec = doRowColPermutationDecryption(enc, rowList, colList)





Before permuation
 [[50. 55. 60. 65.]
 [49. 54. 59. 64.]
 [48. 53. 58. 63.]
 [47. 52. 57. 62.]]

after row permuation
 [[49. 54. 59. 64.]
 [50. 55. 60. 65.]
 [47. 52. 57. 62.]
 [48. 53. 58. 63.]]

after row col
 [[59. 49. 64. 54.]
 [60. 50. 65. 55.]
 [57. 47. 62. 52.]
 [58. 48. 63. 53.]]

Before dedpermuation
 [[59. 49. 64. 54.]
 [60. 50. 65. 55.]
 [57. 47. 62. 52.]
 [58. 48. 63. 53.]]

after col de permuation
 [[49. 54. 59. 64.]
 [50. 55. 60. 65.]
 [47. 52. 57. 62.]
 [48. 53. 58. 63.]]

after per
 [[50. 55. 60. 65.]
 [49. 54. 59. 64.]
 [48. 53. 58. 63.]
 [47. 52. 57. 62.]]
